data:
  params:
    dataset: synth
    subsample: [1,2,3,4,5,6,7,8,9,10,20,50,100]
    seed:
      id: ['indep', 'x_cause_y']
  options:
    path: ../data/synth
    scriptname: prepare_synth
    envname: crunch

results:
  name: synth_run1
  plots: False
  metrics:
    - F1
    - AUROC
  repeats: 1

algorithms:
  - id: dummy
    script:
      file: dummy/dummy.py
      env: dodiscover
  
  - id: var
    hparams:
      lag: [1,2,3,4,5,10,20]
      sum: ['max']
    script:
      file: var/var.py
      env: ../envs/var.yml
  
  - id: dynotears
    hparams:
      lag: [1,2,3,4,5,10,20]
      w_thres: [0.01]
      lambda_w: [0.05]
      lambda_a: [0.05]
    script:
      file: dynotears/main.py
      env: ../envs/causalnex.yml
  
  - id: pcmci
    hparams:
      lag: [1,2,3,4,5,10,20]
      alpha: [0.05]
    script:
      file: tigramite/main.py
      param: pcmci
      env: tigramite

  - id: varlingam
    hparams:
      lag: [1,2,3,4,5,10,20]
      alpha: [0.05]
    script:
      file: lingam/main.py
      env: lingam